spring:
  application:
    name: user-service
server:
  port: 3032

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true
